import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[shell]
program="/bin/zsh"

[window]
padding={x=10,y=10}
dynamic_padding=false
decorations="None"
opacity=0.8

[scrolling]
history=100000

[font]
size=12
normal={family="FiraCode Nerd Font", style="Regular"}
bold={family="FiraCode Nerd Font", style="Bold"}
italic={family="FiraCode Nerd Font", style="Italic"}
offset={x=0, y=0}

[mouse]
hide_when_typing=true
